## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
my_array = np.random.randint(0, 10, 18)
print(my_array)

my_array[(3 <= my_array) & (my_array <= 8)] *= -1
print(my_array)

[9 2 7 3 4 1 5 9 4 0 1 7 1 7 0 1 2 8]
[ 9  2 -7 -3 -4  1 -5  9 -4  0  1 -7  1 -7  0  1  2 -8]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
print(my_array, f'max value is: {my_array.max()}')
my_array[my_array == my_array.max()] = 0
print(my_array)

[ 9  2 -7 -3 -4  1 -5  9 -4  0  1 -7  1 -7  0  1  2 -8] max value is: 9
[ 0  2 -7 -3 -4  1 -5  0 -4  0  1 -7  1 -7  0  1  2 -8]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [462]:
my_array = np.random.randint(0, 6, (3, 2))
print(f"my_array:\n{my_array}\n")

grid = np.meshgrid(*my_array, indexing='ij')

result = np.array(grid).T.reshape(-1, len(my_array))

print(f"result:\n{result}")



my_array:
[[5 3]
 [2 3]
 [5 5]]

result:
[[5 2 5]
 [3 2 5]
 [5 3 5]
 [3 3 5]
 [5 2 5]
 [3 2 5]
 [5 3 5]
 [3 3 5]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [46]:
A_array = np.random.randint(0, 4, (8, 3))
B_array = np.random.randint(0, 4, (2, 2))
print("A_array:\n", A_array)
print("\nB_array:\n", B_array)

B_unique = np.unique(B_array)
print("\nUnique values in B_array: ", B_unique)

for row in A_array:
    flag = 0
    for i in B_unique:
        if i not in row:
            flag = 1
            break
    if flag == 0:
        print(row)

result = np.array([row for row in A_array if all(i in row for i in B_unique)])
print("\nResult:\n", result)
        

A_array:
 [[0 3 0]
 [1 1 2]
 [3 0 1]
 [3 2 1]
 [3 3 0]
 [0 1 0]
 [2 0 1]
 [3 1 1]]

B_array:
 [[3 1]
 [1 2]]

Unique values in B_array:  [1 2 3]
[3 2 1]

Result:
 [[3 2 1]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [149]:
my_matrix = np.random.randint(0, 4, (10, 3))
print("Original array:\n", my_matrix)
 
indices = [len(np.unique(row)) > 1 for row in my_matrix]
result = my_matrix[indices]
print("\nResult array:\n", result)

Original array:
 [[0 3 0]
 [0 3 3]
 [1 1 1]
 [3 2 0]
 [2 2 1]
 [3 3 3]
 [3 3 0]
 [3 0 1]
 [0 2 1]
 [1 3 1]]

Result array:
 [[0 3 0]
 [0 3 3]
 [3 2 0]
 [2 2 1]
 [3 3 0]
 [3 0 1]
 [0 2 1]
 [1 3 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [108]:
my_matrix = np.random.randint(0, 3, (8, 3))
print("my_matrix:\n", my_matrix)

indices = ['True']*len(my_matrix)
indices = set()
for i, row_i in enumerate(my_matrix):
    for j, row_j in enumerate(my_matrix[i + 1:], start = i + 1):
        if np.array_equal(row_j, row_i):
            indices.add(j)
            indices.add(i)

print('\nindices:', indices)
result = np.delete(my_matrix, list(indices), axis=0)
print('\nresult:\n', result)

my_matrix:
 [[0 0 2]
 [1 2 0]
 [1 2 0]
 [2 2 1]
 [0 0 0]
 [2 0 0]
 [1 1 0]
 [1 0 2]]

indices: {1, 2}

result:
 [[0 0 2]
 [2 2 1]
 [0 0 0]
 [2 0 0]
 [1 1 0]
 [1 0 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [205]:
mtr = np.random.randint(0, 4, (5, 4))
print(f"Matrix:\n{mtr}\n")
# NumPy
values = mtr[np.arange(min(mtr.shape)), np.arange(min(mtr.shape))]
values = values[values != 0]

print(f"values: {values}")
result = np.prod(values)
print(f"result: {result}\n")

# Python
mtr = mtr.tolist()
print(f"Matrix:\n{mtr}\n")

result = 1
for i in range(min(len(mtr), len(mtr[0]))):
    if mtr[i][i] != 0:
        result *= mtr[i][i]
print(f"result: {result}")

Matrix:
[[1 3 1 2]
 [1 0 1 0]
 [0 0 3 2]
 [3 2 0 2]
 [1 3 2 1]]

values: [1 3 2]
result: 6

Matrix:
[[1, 3, 1, 2], [1, 0, 1, 0], [0, 0, 3, 2], [3, 2, 0, 2], [1, 3, 2, 1]]

result: 6


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [317]:
x = np.random.randint(0, 2, 4)
y = np.random.randint(0, 2, 4)
print(f"x: {x}\ny: {y}")

# NumPy
print("Numpy result: ", np.all(np.array_equal(np.sort(x), np.sort(y))))

# Python

x = sorted(x.tolist())
y = sorted(y.tolist())

print("Result Python: ", x == y)

x: [1 1 1 0]
y: [1 1 1 0]
Numpy result:  True
Result Python:  True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [406]:
vec = np.random.randint(0, 10, 18)
print("vec: ", vec)
# Numpy
values = vec[np.where(vec[:-1] == 0)[0] + 1]

print(values)
print("NumPy max: ", values.max()) if len(values != 0) else print("No elements on the right of 0.")

# Python
vec = vec.tolist()
print("vec: ", vec)

values = [vec[index + 1] for index, value in enumerate(vec) if value == 0 and index != len(vec) - 1]

print(values) 
print("Python max: ", max(values)) if len(values) != 0 else print("No elements on the right of 0.")

vec:  [4 1 1 6 4 6 3 5 7 2 4 5 2 9 4 6 5 7]
[]
No elements on the right of 0.
vec:  [4, 1, 1, 6, 4, 6, 3, 5, 7, 2, 4, 5, 2, 9, 4, 6, 5, 7]
[]
No elements on the right of 0.


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [477]:
from collections import Counter

x = np.sort(np.random.randint(0, 10, 18))
print(f"x: {x}")

# NumPy
values, times = np.unique(x, return_counts=True)
print(f"values: {values}\ntimes: {times}\n")

# Python
x = x.tolist()

print(f"values: {tuple(Counter(x).keys())}\ntimes: {tuple(Counter(x).values())}")


x: [2 2 3 3 4 4 4 5 5 6 6 6 7 8 8 8 9 9]
values: [2 3 4 5 6 7 8 9]
times: [2 2 3 2 3 1 3 2]

values: (2, 3, 4, 5, 6, 7, 8, 9)
times: (2, 2, 3, 2, 3, 1, 3, 2)


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [ ]:
# Skip

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [437]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [441]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [446]:
average_calories = np.mean(calorie_stats)
print(average_calories)

106.88311688311688


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [445]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [448]:
median_calories = np.median(calorie_stats)
print("median_calories: ", median_calories)
print("average_calories", average_calories)

median_calories:  110.0
average_calories 106.88311688311688


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [466]:
for i in range(0, 10, 1):
    print(f"{i}_percentile = {np.percentile(calorie_stats, i)}")
    if np.percentile(calorie_stats, i) >= 60:
        nth_percentile = np.percentile(calorie_stats, i)
        break
print(f"\nnth_percentile: {nth_percentile}")

0_percentile = 50.0
1_percentile = 50.0
2_percentile = 50.0
3_percentile = 55.599999999999994
4_percentile = 70.0

nth_percentile: 70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [475]:
count_above_60 = np.sum(calorie_stats > 60)
count_all = calorie_stats.size
more_calories = (count_above_60 / count_all) * 100

print(f"more_calories: {more_calories:.2f} %")


more_calories: 96.10 %


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [476]:
calorie_std = np.std(calorie_stats)
print(f"caloie_std: {calorie_std}")

caloie_std: 19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [479]:
"""
    Кол-во калорий в хлопьях наших конкурентов: mean = 106.88, median = 110.
    Более 96% конкурентов имеют калорийность хлопьев выше наших 60.
    Разнообразие предложений наших конкурентов относительно среднего значения отличается на 19.36 (std).
"""

'\n    Кол-во калорий в хлопьях наших конкурентов: mean = 106.88, median = 110.\n    Более 96% конкурентов имеют калорийность хлопьев выше наших 60.\n    Разнообразие предложений наших конкурентов относительно среднего значения отличается на 19.36 (std).\n'